Type=Exe
Module=read_RDB; nmr_dict.bas
Reference=*\G{00020430-0000-0000-C000-000000000046}#2.0#0#..\..\..\..\WINDOWS\SYSTEM\STDOLE2.TLB#OLE Automation
Module=rdBMRB_schema; rdbmrb_dict.bas
Module=write_dict; write_dict.bas
Module=start; start.bas
Module=read_NMR_dep; rd_NMR_Dep.bas
Module=table_update; table_update.bas
Module=rd_dict; ..\htmldocs\nmr_star\dictionary_files\rd_dict.bas
Module=rd_enumer; ..\htmldocs\nmr_star\dictionary_files\rd_enumer.bas
Module=write_grps; write_grps.bas
Startup="Sub Main"
Command32=""
Name="NMR_STAR_Dict"
HelpContextID="0"
CompatibleMode="0"
MajorVer=1
MinorVer=0
RevisionVer=0
AutoIncrementVer=0
ServerSupportFiles=0
VersionCompanyName="Univ. of Wisconsin"
CompilationType=0
OptimizationType=0
FavorPentiumPro(tm)=0
CodeViewDebugInfo=0
NoAliasing=0
BoundsCheck=0
OverflowCheck=0
FlPointCheck=0
FDIVCheck=0
UnroundedFP=0
StartMode=0
Unattended=0
ThreadPerObject=0
MaxNumberOfThreads=1

[MS Transaction Server]
AutoRefresh=1
